# Generated by Django 2.1.2 on 2018-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_info', '0002_auto_20181005_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
